### ISSUE TITLE
Remove permission to unmute for leaders of another section

### ISSUE THREAD

**Issue by Deaththth** [ToogaInc/ToogaBooga#109] opened 2022-02-19 10:54 UTC
Currently leaders of any section have server unmute permissions in vet raids. This permission should be removed.

**Comment by ewang2002** [comment] 2022-03-12 10:23
From my understanding, this should only happen if one of the following are true:
- you assigned some leader role as a *universal leader role*. When you assign a leader role as a universal leader role, anyone with that role will be able to mute/deafen anyone in all sections.
- you gave leader roles server mute/deafen permissions through Discord's role menu. 

Can you double check and validate this? Otherwise, I'm not too sure what the issue is since the bot is developed so that, when you put a raid in some section, only that section's leader roles *and* the universal leader roles should have the correct permissions.

**Comment by ewang2002** [comment] 2022-08-12 19:55
Closing as invalid. 

If this is an issue, remove the leader's permissions to mute/deafen via Discord's role menu. Then, in the `configafkcheck` command, allow the section leaders the ability to mute/deafen.

**Closed by ewang2002** 2022-08-12 19:55 UTC
Labels: it-enhancement, o-unverified, c-raid, c-config
